name: Deploy NeuroEdu to Firebase Hosting

on:
  push:
    branches:
      - main # Activa el deploy siempre que hagas un Push formal a tu rama maestro

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Context
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependencias del Paquete Angular
        run: npm ci --legacy-peer-deps # Usa CI para velocidad, con legacy para resolver conflictos de @angular/fire

      - name: Compilar Código de Producción
        run: npm run build -- --configuration production

      - name: Desplegar Artefacto en Firebase Hosting
        run: npx firebase-tools deploy --only hosting --project classroom-developz --token ${{ secrets.FIREBASE_TOKEN }}
